version: '3.8'

services:
  backend:
    build: .
    ports:
      - "8000:8000"
    environment:
      - ENV=dev
    volumes:
      - .:/app

  frontend:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./app/static:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
